obj-$(CONFIG_OTA_UPGRADE) += ota_upgrade.o ota_image.o ota_manifest.o \
			     ota_storage.o ota_breakpoint.o
obj-y += ota_backend_bt.o
obj-y += ota_backend_sdcard.o
obj-y += ota_backend_temp_part.o
obj-$(CONFIG_OTA_FILE_PATCH) += ota_file_patch.o hpatch.o
obj-$(CONFIG_OTA_BACKEND_UART) += ota_backend_uart.o
obj-y += libota_version.o
