@echo off

if exist "doc" rd/s/q "doc"

if exist "drivers\clock_control" del /F /S /Q "drivers\clock_control\*.c"
if exist "drivers\clock_control" del /F /S /Q "drivers\clock_control\*.h"
if exist "drivers\counter" del /F /S /Q "drivers\counter\counter*.*"
if exist "drivers\counter" del /F /S /Q "drivers\counter\timer*.*"
if exist "drivers\crypto" del /F /S /Q "drivers\crypto\crypto*.*"
if exist "drivers\ethernet" del /F /S /Q "drivers\ethernet\eth_*.*"
if exist "drivers\ethernet" del /F /S /Q "drivers\ethernet\phy_sam_gmac.*"
if exist "drivers\flash" del /F /S /Q "drivers\flash\flash_stm32*.*"
if exist "drivers\grove" del /F /S /Q "drivers\grove\*.c"
if exist "drivers\i2c" del /F /S /Q "drivers\i2c\i2c_ll_stm32*.*"
if exist "drivers\ieee802154" del /F /S /Q "drivers\ieee802154\*.c"
if exist "drivers\ieee802154" del /F /S /Q "drivers\ieee802154\*.h"
if exist "drivers\interrupt_controller" del /F /S /Q "drivers\interrupt_controller\*.c"
if exist "drivers\interrupt_controller" del /F /S /Q "drivers\interrupt_controller\*.h"
if exist "drivers\pinmux\beetle" rd/s/q "drivers\pinmux\beetle"
if exist "drivers\pinmux\dev" rd/s/q "drivers\pinmux\dev"
if exist "drivers\pinmux" del /F /S /Q "drivers\pinmux\pinmux*.c"
if exist "drivers\pinmux\stm32" del /F /S /Q "drivers\pinmux\stm32\*.*"

if exist "drivers\sensor\adxl362" rd/s/q "drivers\sensor\adxl362"
if exist "drivers\sensor\ak8975" rd/s/q "drivers\sensor\ak8975"
if exist "drivers\sensor\apds9960" rd/s/q "drivers\sensor\apds9960"
if exist "drivers\sensor\bma280" rd/s/q "drivers\sensor\bma280"
if exist "drivers\sensor\bmc150_magn" rd/s/q "drivers\sensor\bmc150_magn"
if exist "drivers\sensor\bme280" rd/s/q "drivers\sensor\bme280"
if exist "drivers\sensor\bmi160" rd/s/q "drivers\sensor\bmi160"
if exist "drivers\sensor\bmg160" rd/s/q "drivers\sensor\bmg160"
if exist "drivers\sensor\bmm150" rd/s/q "drivers\sensor\bmm150"
if exist "drivers\sensor\dht" rd/s/q "drivers\sensor\dht"
if exist "drivers\sensor\fxas21002" rd/s/q "drivers\sensor\fxas21002"
if exist "drivers\sensor\fxos8700" rd/s/q "drivers\sensor\fxos8700"
if exist "drivers\sensor\hdc1008" rd/s/q "drivers\sensor\hdc1008"
if exist "drivers\sensor\hmc5883l" rd/s/q "drivers\sensor\hmc5883l"
if exist "drivers\sensor\hp206c" rd/s/q "drivers\sensor\hp206c"
if exist "drivers\sensor\hts221" rd/s/q "drivers\sensor\hts221"
if exist "drivers\sensor\isl29035" rd/s/q "drivers\sensor\isl29035"
if exist "drivers\sensor\lis2dh" rd/s/q "drivers\sensor\lis2dh"
if exist "drivers\sensor\lis3dh" rd/s/q "drivers\sensor\lis3dh"
if exist "drivers\sensor\lis3mdl" rd/s/q "drivers\sensor\lis3mdl"
if exist "drivers\sensor\lps22hb" rd/s/q "drivers\sensor\lps22hb"
if exist "drivers\sensor\lps25hb" rd/s/q "drivers\sensor\lps25hb"
if exist "drivers\sensor\lsm6ds0" rd/s/q "drivers\sensor\lsm6ds0"
if exist "drivers\sensor\lsm6dsl" rd/s/q "drivers\sensor\lsm6dsl"
if exist "drivers\sensor\lsm9ds0_gyro" rd/s/q "drivers\sensor\lsm9ds0_gyro"
if exist "drivers\sensor\lsm9ds0_mfd" rd/s/q "drivers\sensor\lsm9ds0_mfd"
if exist "drivers\sensor\max30101" rd/s/q "drivers\sensor\max30101"
if exist "drivers\sensor\max44009" rd/s/q "drivers\sensor\max44009"
if exist "drivers\sensor\mcp9808" rd/s/q "drivers\sensor\mcp9808"
if exist "drivers\sensor\mpu6050" rd/s/q "drivers\sensor\mpu6050"
if exist "drivers\sensor\nrf5" rd/s/q "drivers\sensor\nrf5"
if exist "drivers\sensor\sht3xd" rd/s/q "drivers\sensor\sht3xd"
if exist "drivers\sensor\sx9500" rd/s/q "drivers\sensor\sx9500"
if exist "drivers\sensor\th02" rd/s/q "drivers\sensor\th02"
if exist "drivers\sensor\tmp007" rd/s/q "drivers\sensor\tmp007"
if exist "drivers\sensor\tmp112" rd/s/q "drivers\sensor\tmp112"
if exist "drivers\wifi\rtl8189ftv" rd/s/q "drivers\wifi\rtl8189ftv"
if exist "drivers\wifi\ssv6030p" rd/s/q "drivers\wifi\ssv6030p"

if exist "tests\benchmarks" rd/s/q "tests\benchmarks"
if exist "tests\bluetooth" rd/s/q "tests\bluetooth"
if exist "tests\booting" rd/s/q "tests\booting"
if exist "tests\compliance" rd/s/q "tests\compliance"
if exist "tests\crypto" rd/s/q "tests\crypto"
if exist "tests\drivers" rd/s/q "tests\drivers"
if exist "tests\include" rd/s/q "tests\include"
if exist "tests\kernel" rd/s/q "tests\kernel"
if exist "tests\lib" rd/s/q "tests\lib"
if exist "tests\net" rd/s/q "tests\net"
if exist "tests\power" rd/s/q "tests\power"
if exist "tests\shell" rd/s/q "tests\shell"
if exist "tests\subsys" rd/s/q "tests\subsys"
if exist "tests\unit" rd/s/q "tests\unit"
if exist "tests\ztest\include" rd/s/q "tests\ztest\include"
if exist "tests\ztest\src" rd/s/q "tests\ztest\src"
if exist "tests\ztest\test" rd/s/q "tests\ztest\test"

pause
